### ISSUE TITLE
Get factors summary fails with MTBLS200

### ISSUE THREAD

**Issue by pcm32** [phnmnl/container-mtblisa#4]
Hi @djcomlab I think I have hit a glitch with MTBLS200 when using get factors summary. Error is:

```
Setting material objects: 0 of 66 |                            | ETA:  --:--:--
                                                                               

Setting material objects: 66 of 66 |############################| Time: 0:00:00
2017-07-11T09:01:49.074752413Z 
                                                                               

Generating process objects: 0 of 66 |                          | ETA:  --:--:--Traceback (most recent call last):
2017-07-11T09:01:49.074792851Z   File "/usr/local/bin/run_mtblisa.py", line 131, in <module>
2017-07-11T09:01:49.074810991Z     summary = MTBLS.get_study_variable_summary(study_id)
2017-07-11T09:01:49.074815231Z   File "/usr/local/lib/python3.5/dist-packages/isatools/io/mtbls.py", line 393, in get_study_variable_summary
2017-07-11T09:01:49.074818655Z     ISA = load(mtbls_study_id=mtbls_study_id)
2017-07-11T09:01:49.07482154Z   File "/usr/local/lib/python3.5/dist-packages/isatools/io/mtbls.py", line 239, in load
2017-07-11T09:01:49.074824263Z     ISA = isatab.load(f)
2017-07-11T09:01:49.074826569Z   File "/usr/local/lib/python3.5/dist-packages/isatools/isatab.py", line 2905, in load
2017-07-11T09:01:49.074829291Z     study_factors=study.factors).create_from_df(assay_tfile_df)
2017-07-11T09:01:49.074831495Z   File "/usr/local/lib/python3.5/dist-packages/isatools/isatab.py", line 3453, in create_from_df
2017-07-11T09:01:49.074833776Z     raise ValueError("Could not resolve Protocol parameter from Parameter Value ", category_key)
2017-07-11T09:01:49.074836115Z ValueError: ('Could not resolve Protocol parameter from Parameter Value ', 'Post Extraction')
```

when executing:

```
run_mtblisa.py --command GET_SUMMARY --study MTBLS200
```

This should be on the latest built mtblisa container.

Thanks!

**Comment by djcomlab** [comment]
Sure, this is a problem with MTBLS200 itself actually as protocol parameter 'Post Extraction' indicated in the Parameter Value in the assay file is not declared in the Study Protocol Parameters section in the investigation file.

**Comment by pcm32** [comment]
We have passed this to MetaboLights curators.

**Comment by djcomlab** [comment]
Closing as this is an issue with the MTBLS data rather than the ISA-Tab parser.
